before_install:
 - gem install cocoapods
install:
 - brew update && brew upgrade swiftlint
 - pod install
language: swift
osx_image: xcode12.2
xcode_workspace: Dash Monkey.xcworkspace # path to your xcodeproj folder
script:
 - swiftlint
